### ISSUE TITLE
Search & Discovery -  When multiple categories selected, listing results need to be union of sets

### ISSUE THREAD

**Issue by jloveland18** [ozone-development/ozp-center#185]
In center, the search field doesn't search the apps Database, but refines the Existing Category. For a user to execute a full search on all apps, they must Understand to clear all Categories (or select 'home') before attempting a find.

**Comment by sdeighan** [comment]
This will be improved by the addition of the search parameters ( #161 ) so that it's more obvious what categories are being searched within and what keywords are being used. It will also be easier to reset a particular criterium or all criteria.

Did you have another feature that you were interested in having added? I don't know what you would like done in order to enhance the search.

**Comment by tonyalletag** [comment]
This is a customer request. I think the we are going to be forced to make this function as "OR" instead of "And". We can talk about timeline and implementation if needed.

**Comment by sdeighan** [comment]
Ok, so this is about how the filters work? They're interested in having the filters act as a Union of two sets rather than an Intersection? Because the "refinement" part will not change, it's only a matter of the visibility of the category or categories being searched in. Every search is just a refinement.

**Comment by tonyalletag** [comment]
This may cause more confusion if we change this now.
