### ISSUE TITLE
Create/Edit Page - Screenshots are only throwing errors for one screenshot image at a time

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-center#188]
I added an image to the Preview Image that was greater then 1MB and tried to hit save and got an error for the Preview image. Then for the Full Size image I entered an invalid image type (bmp) and hit Save. I expected to see errors for both images I uploaded but I only saw an error for the Full Size image and not the Preview Image this time.

**Comment by akonsowski** [comment]
@bhalt can you take a look at the alert message
if the image is not the specified file type
![image](https://cloud.githubusercontent.com/assets/18122042/15714323/19fbb1b4-27e8-11e6-9e42-d6e25fc84efd.png)
if the image is too big
![image](https://cloud.githubusercontent.com/assets/18122042/15714342/2ac7f354-27e8-11e6-980e-962c583a392f.png)

**Comment by bhalt** [comment]
@akonsowski I assume this is tapping into the alert JS already used on that page?

Three suggestions on the language -

* **un**capitalize the "upload" in both titles
* all caps on "JPG, PNG, or GIF" (no "e" needed in JPG, those are interchangable but JPG more common)
* remove the space before the final period in both sentences

Looks good - thanks!

**Comment by tdressel** [comment]
Followed above testing steps:

I added a jpg over 1 MB for Preview and a BMP ( invalid format) for Full size image.
I received errors for both individually.
I try to save the form and received a pop up," Could not save! Your listing could not be saved because you have errors!"
Both fields say ,"Must be a .png, .jpg, or .gif file and must be smaller than 1MB."

PASSED on latest.

**Comment by tdressel** [comment]
Passed on Staging.
