### ISSUE TITLE
Listing Management - Numbers Disappear when you select state

### ISSUE THREAD

**Issue by jloveland18** [ozone-development/ozp-center#209]
1. Got to listing Management.
2. Select My Listings.
3. Select All, then Published, then needs action.
4. Notice that you always see how many are in each state.
5. Go to all Marketplace Listings.
6. All is Highlighted and you see the numbers of Listings in each state. Select Published. Notice that you see how many are in the Published state, but all the rest of the numbers Disappear for every other state.
7. Select Pending, org. Notice that you see how many are in the pending state, but all the rest of the numbers by the states Disappear.

**Comment by jloveland18** [comment]
This is in Chrome, FF and IE.

**Comment by mparizernc** [comment]
@jloveland18  This is the intended behavior the numbers were removed to avoid confusion of having numbers for the other statuses since one particular status was filtered. The counts would all be 0 anyhow. So this is not a bug perhaps it is open for discussion if it should work this way but this is the intended behavior.

**Comment by clarkjefcoat** [comment]
At least part of this issue is the inconsistency.  In "My Listings" if you select "Published" you still see the other numbers:

![image](https://cloud.githubusercontent.com/assets/7015118/7297177/7b84083e-e994-11e4-90e6-72f76078cdc7.png)

However, in "All Marketplace Listings" the numbers disappear

![image](https://cloud.githubusercontent.com/assets/7015118/7297194/a001f5f4-e994-11e4-8e5d-dbf13cde89cc.png)

**Comment by sdeighan** [comment]
So, this was on purpose.
The reasoning behind it is that in "My Listings" the only filter is the "State" filter. Therefore, if you are in the middle of working with your listings, if you click on the "Needs Action" state filter, the number will be accurate. We thought that these numbers would be helpful. The response seems to be positive.

If you are working with the "Marketplace Listings", there is a variety of filters. If you select "Published" and then "NTO", you have selected only those listings which are in both "Published" and "NTO". So, the "Needs Action" filter will display '0', since no listing can be in both states. However, clicking "Needs Action" switches that filter from "Published" to "Needs Action". So, if the number were accurate for what would be shown, like it is in "My Listings", it would be greater than '0'. But that's impossible when "Published" is selected.

After trying several different iterations of what the numbers would show, we decided that the confusion was not worth it. However, it was still useful and clear in "My Listings" because that is the only filter. As to it being inconsistent between screens, the average user will never see "Marketplace Listings" or the "Organization's Listings" tabs and the average Steward will not have listings of their own. Although visible during testing, very few users, if any, will be confronted by the differences while they work with the system.

The added functionality under "Marketplace Listings"  and "Organization's Listings," while different, is a more advanced area. The added functionality changes the look a little bit, but it seemed a reasonable trade-off. We can't really add numbers to "My Listings", due to the difficulties previously discussed. We can remove the numbers on "My Listings" but it would be removing a seemingly useful feature.
