### ISSUE TITLE
Most Popular Carousel Missing

### ISSUE THREAD

**Issue by TheAndyStumpf** [ozone-development/ozp-center#216]
Most Popular apps need to be on a carousel like New Arrivals.

**Comment by sdeighan** [comment]
Unfortunately, they are the ones that populate downward that we were going to convert to the infinite scroll. Since we don't have metrics, we can't really make that infinite scroll section into "Recommended". "Most Popular" seemed to be the applications worthiest of highlight on the homepage. Did you have a suggestion for what other group should populate the rest of the page? Or would you rather it be left blank?
