### ISSUE TITLE
Move Listing Type and Organizations back to Faceting column

### ISSUE THREAD

**Issue by TheAndyStumpf** [ozone-development/ozp-center#217]
Listing Type and Organizations were previously structured like categories.  Having them on the other side of the search bar creates extra work for the user by requiring them to traverse across the page to select or deselect options.  Putting them back in the Faceting column, with filtering capability like categories, creates a smoother UX.

Definitely a post-IOB task.

**Comment by sdeighan** [comment]
Unfortunately there are many reasons that led to those filters being in the main bar. The primary two reasons are 1.) that you wanted to support "Browsing" equally with "Searching" and 2.) that there is a limited amount of space in the left hand column. Moving those two filters over take up a lot of space in the column. In order to accommodate them and the categories, we need to do one of two things.

Firstly, we can change the categories to be a simple dropdown menu. It becomes a very 'search' style pattern that removes the "browsing" feeling of the large buttons and leaves the UI very search-centric. Categories become just another search filter. If you are ok with supporting "Searching" over "Browsing" then this is an excellent route to go.

Secondly, we can keep the categories large and very browsing friendly. However, there are many categories and they all have long names. Since we cannot restrict the number of categories, we cannot give Listing Types or Organizations enough space in the column for them to be visible at the same time. So, to allow people to browse or search, we will need to implement an accordion tab system to allow Listing Types and Organizations to have the same inherent aesthetic weight and visibility as Categories. This, unfortunately, becomes a problem when multiple fields are selected. Unless we add a neutral "smart" area that keeps track of criteria (also very "search" oriented), a user will have to remember all the criteria he has selected and go back and forth between all the tabs to have a fully functional search. It would double or triple the number of interactions that a user would have to go through if they wanted to filter a search by more than one criteria, such as "Categories" and "Listing Types". It has the smoothest look, but requires the most clicks for a user to perform a simple task and runs the highest risk for user frustration and rejection of the interaction style.

If anyone has additional ideas, I would love to discuss them in detail.

If you would really like them over in the left column, I would highly suggest that we pursue researching how our users prefer to interact with our system. Then, we can know if switching to a primarily "Search" oriented interface would be a benefit or a potential issue.

**Comment by tonyalletag** [comment]
Lets wait till after IOB to to hear what the user feedback is on this

**Comment by tonyalletag** [comment]
No an issue
