### ISSUE TITLE
Create/Edit Page Secure and Unsecure number red highlight turns off and on

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-center#229]
Creating a listing, populate the required fields.  Add New Contact,
typing in the number fields cause the red highlight to blink on and off which is distracting.  Found in staging and ci-master

**Comment by sdeighan** [comment]
At the moment, I believe that phone numbers flash most because they accept both 7 digit and 10 digit numbers. Perhaps we could get the form fields to attempt validation once focus is off a field? @arw180 @stephanieerin @wski @hoganmaps Would that work? Or is there another or a better solution for this?

**Comment by stephanieerin** [comment]
This is the intended functionality. You're going from an invalid phone number (less than 7 characters) to a valid one (7) to an invalid one (8-10) to another valid one (10). This should be reflected in the highlighting of errors.

**Comment by wski** [comment]
Can this be closed? cc @tonyalletag @clarkjefcoat
