### ISSUE TITLE
GH-Pages Error in Center

### ISSUE THREAD

**Issue by emosher** [ozone-development/ozp-center#239]
I'm trying to see if webtop fits my needs, but after cloning and running it I need to go to center because I have no apps.  When I visit center it takes me to the Github pages site at http://ozone-development.github.io/ozp-center/#/home.  I get the following screen: 

![ozp-center-error](https://cloud.githubusercontent.com/assets/1850338/7570453/586ac132-f7de-11e4-8645-f7d3e175f7c5.png)

When I open up the console, I can see that this is a CORS error as shown below.

![ozp-center-console](https://cloud.githubusercontent.com/assets/1850338/7570462/6d53ab68-f7de-11e4-91d4-1d529ed9e2da.png)

Any help would be appreciated.  I'm most interested in webtop, not center but this stops me from trying it much.

**Comment by arw180** [comment]
The `owfgoss` infrastructure went down a couple of weeks ago, and since the gh-pages demos rely on a backend hosted on `owfgoss`, none of the gh-pages demos work at the moment. Thanks for the reminder that we need to update READMEs to indicate the issue. 

The easiest way to test this out locally is to use Vagrant as per the instructions here: https://github.com/ozone-development/dev-tools/tree/master/vagrant/centos6.6/build-and-deploy-box

There are also a couple of CI servers running that you may have access to - I'll send you more details via email.

**Comment by wski** [comment]
As an effect to what is mentioned above the gh-pages branch has been removed to help resolve confusion

**Comment by mparizernc** [comment]
@wski shouldn't we remove all of the demo pages as well?

**Comment by wski** [comment]
@mparizernc if we are not going to support them for now I would just leave the website and disable the links to the gh-pages; I think @arw180 is planning to stand everything back up when the new backend exists so we should keep the main site. 

@tonyalletag @clarkjefcoat What do you guys think?

**Comment by clarkjefcoat** [comment]
We should remove any links to non-working pages.  Keeping main page at http://ozone-development.github.io/ is fine, but it shouldn't have bad links.

**Comment by mparizernc** [comment]
@clarkjefcoat The only links that work are the ones at the bottom of the page. None of the tools work (HUD, Webtop, Center, Metrics). Of course the sample widgets won't work if they use IWC because there is no back end.  It might make sense to just disable to page until there is a back end that can be run.

**Comment by tonyalletag** [comment]
We should shutdown this page and redirect people to http://ozone-development.github.io/ozone-website/

**Comment by wski** [comment]
done :+1:

**Comment by jal-vsi** [comment]
GH page eliminated bad (demo) link.  LInks to URL with old (OWF) and new (OZP) data.
