### ISSUE TITLE
Discovery Page - Search results not obvious when searching after scrolling

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#289]
To reproduce:

1.  Type something in the search bar that gives results.
2.  Scroll down and select a category that narrows down the search results (or produces no search results).
3.  You see nothing but white in the area where you expect to see search results.  Your search results, if any, are not visible unless you scroll up.

The screenshot below shows this issue if your browser is fairly short.  In production where we have many more categories this issue is common.

![image](https://cloud.githubusercontent.com/assets/7015118/8184719/ef2799c4-140d-11e5-9585-e8b424156877.png)

**Comment by bhalt** [comment]
To work with the current scrolling layout, could we solve this issue by automatically scrolling to the top when a category is selected? I'm a little worried about a selected filter then being hidden below the fold, but think this is the preferred behavior rather than moving navigation. @sdeighan, thoughts?

**Comment by sdeighan** [comment]
I'm also a little worried about it; I would feel more comfortable with it once we get the search criteria feature implemented (the one that lists all the search terms and filters over above the search results). Unfortunately, there will be a problem either way until the search criteria is implemented. We can add the scroll, but it will prevent the selected category from being seen.  In it's current state, the reaction of the system is a direct 1 to 1 response to a request and the category can immediately be de-selected if there's a problem. Otherwise, every time the user selects, they will need to scroll back to what they were doing. I would rather put the development effort into the criteria feature first and then consider implementing the scroll up at that time.

**Comment by bhalt** [comment]
I would agree that the criteria/scroll combo solution would be ideal! I don't think the criteria alone would solve this specific issue, but I would be much more comfortable with the scroll if the criteria were implemented. I don't think the criteria feature would be hard to implement either since all of the data is already pulled in - @clarkjefcoat?

**Comment by sdeighan** [comment]
![mp_searchanddiscovery_searchresults](https://cloud.githubusercontent.com/assets/7987446/8192178/725dd976-143a-11e5-8c32-1a0b716b41d9.png)

**Comment by clarkjefcoat** [comment]
Thanks.  I like this criteria/scroll combo solution.  I'll talk with the team here to see how difficult they think the criteria feature will be.

**Comment by wski** [comment]
I don't think it would be considerably hard to manage both, I'll knock this out soon. However I do think scrolling to the top after each category change is going to be a bit undesirable, but tolerable until we think of a better solution. The criteria looks great and will help clarify what is actually happening when users click things.

**Comment by sdeighan** [comment]
We can think about the scrolling thing a little bit more but Bethany and I agree that we would prefer it not scroll up after each category change until there are criteria. Unfortunately, she is out of the office right now, but I will bring it up with her when she gets back. Until then, please don't implement the scrolling part without the criteria part. We think that it would cause more problems than it would solve at this point in development.

**Comment by wski** [comment]
@sdeighan I was planning to implement both at the same time

**Comment by mparizernc** [comment]
@wski what exactly was changed and should be tested for this?

**Comment by wski** [comment]
It scrolls to top when a search is completed.

**Comment by mparizernc** [comment]
Verified that in all of the browsers in develop that after each filter is chosen and search string is entered the screen scrolls to the top of the search page.

**Comment by mparizernc** [comment]
Verified in staging that after performing searches and filter selections the search page scrolls back to the top of the page.
