### ISSUE TITLE
Metrics - Search not reporting when a category is selected

### ISSUE THREAD

**Issue by gziskind** [ozone-development/ozp-center#291]
Searches are not being reporting to the metrics interface while there is a categories selected.

**Comment by mparizernc** [comment]
Verified in develop that searches are being reported when categories are being selected first.

**Comment by clarkjefcoat** [comment]
This fix may have unintended consequences in that "Keyword with no search results" will include search terms that have results, but that had no results in combination with the category that was selected.  On the metrics page I don't see a way to tell if the reason a search term had no results was because a category was selected.

**Comment by wski** [comment]
@gziskind Would this be best remedied with a case in piwik or is there a different way I should report "no results because categories are selected"

**Comment by mparizernc** [comment]
In this case would the same thing not happen for Organization and Type if no responses were returned.

**Comment by mparizernc** [comment]
Verified in staging that Search strings are recorded in metrics after Categories are selected.
