### ISSUE TITLE
Add tooltips to app listing quick view and detailed view

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-center#344]
Quick View / Hoover Over - "Launch", "Bookmark"
Detailed View - "Launch", "Bookmark" ,"Edit"

**Comment by sdeighan** [comment]
Just as a historical note, the reason that these items did not have tooltips was for performance. There are so many of them possible in an area, and the hover over is already a hover-based animation, that we were asked to limit animations and tooltips for performance reasons. As I understand it, there are already discrepancies and concerns about the existing tooltips and how they affect performance and are affected by network performance. Just a consideration in adding more tooltips across the system, especially in such a graphics heavy area. Let me know if you need anything else. @tonyalletag @wski

**Comment by wski** [comment]
`how they affect performance and are affected by network performance` I'm not sure how they would cause, or be caused, by any network performance. They are loaded statically with the rest of the application and don't make any serverside calls. 

Though I would agree they are a bit heavy ascetically in `such a graphics heavy area.` I think we could still benefit from them since we don't have any descriptive text under the buttons which could confuse some users.

**Comment by sdeighan** [comment]
We have already proven that they are affected by performance and affect performance via the global toolbar. Whether that is network performance or individual computer performance, it's hard to say, but we have already been able to identify slower speeds of the tooltips appearing on computers at the different locations of the development team. There are certain instances of the product which have even lower system and network capabilities and they will be affected even more.

We also created a specific button style to include a label on hover and specifically chose commonly used icons in order to avoid the need for labels in this area. It is my professional opinion that there will be too many, aesthetically. I would be interested to see how many reports there are of "Bookmark" being misinterpreted. Is there any particular reason that these buttons are more confusing than any other button? Or is the new standard that there should be tooltips on all buttons?

**Comment by tonyalletag** [comment]
This was a customer request there are multiple users on the production system asking for additional tooltips.  I say we try it out since its fairly simple to implement and see if it affects performance. If it does we can quickly remove them, if not we will have some happy users.

**Comment by sdeighan** [comment]
Adding tooltips may not be the best solution. Tooltips themselves are not a feature in themselves - they are an aid when something is unclear. No one wakes in the morning and thinks "Self, what I really need are tooltips to make this better." The permanent, effective, and efficient solution is for the item that is unclear to be made more clear. I understand that proving to users that we hear their requests and we're addressing them buys some brownie points with them and I'm all for getting them to like us more. But as I move off the project, I'd caution to not think of this as a solution but more of an offering of goodwill when what they really need is a UX investigate into the cause of confusion, identify it, and make the item more clear. Bethany can have some fun with this and figure out the means to fix what's really wrong. Otherwise bandaids will continually be sought. The better solution would have less effect on performance and would solve whatever issue sparked the request. I urge you to bring UX in to help craft solutions to address problems like this in the future. Best of luck with the tooltips.

**Comment by jal-vsi** [comment]
Passes testing in Latest and Release environments using IE11, FF24, and CH36.  The 5 Tool tips are available for Quick (2) and Detailed (3) views.

**Comment by tdressel** [comment]
Passed on Staging using Chrome 36, FF 31, IE 10.  Tested Quick(2) and Detailed (3) Views
