### ISSUE TITLE
Contact Modal - Links to social media

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-center#348]
Request from customer to add links to social media:
twitter - 
Pintrest - 
Blog/Website -
Online Chat -

The links or Icons should not show up if the link is empty
The links or icons could go in the common tool bar menu drop down

Looking for UX to decide where these should go. If its in the common tool bar we will have to create tickets for HUD and Webtop

**Comment by sdeighan** [comment]
This was originally suggested previously and at the initial direction-setting was completely pushed off the table by the PMO due to security concerns.

**Comment by bhalt** [comment]
Who's social media links is this for? AML? The user's Org? If AML, maybe this should be a contact page or popup? Not sure adding that many links is a efficient use of real estate. If the org, maybe that should be in their contact details within the app meta.

If AML, I would suggest removing both "Contact Help Desk" and "Give Feedback" links within the global toolbar dropdown -- (not sure when "Contact Help Desk" was added but not sure that really belongs under "Personalize") -- and replacing with a single "Contact" link. This would then pop up a modal giving further guidance, rather than just email address mail-to's within the dropdown. See screenshots:

![contact_dropdown](https://cloud.githubusercontent.com/assets/8047457/9199617/6c9fadcc-4011-11e5-9cd1-1a173d367996.png)

![contact_modal](https://cloud.githubusercontent.com/assets/8047457/9199621/71a083b4-4011-11e5-829b-a4f603bfbc48.png)

Thoughts? Do you think this would solve the issue, @tonyalletag, or are there further needs?

**Comment by bhalt** [comment]
After further discussion, I suggest we also add a link to the Help Desk inside the Help Center. See screenshots for possible options. One mockup shows lesser prominence and one shows more prominence.

The Help Desk link would still be accessible from the Contact modal as shown above. This proposal simply puts all support links/documentation/etc into one easy click from any screen within the platform (the global toolbar help icon). Once the Help Center is built out, this will be a one-stop shop for anything support-related.

![help_helpdesksupport](https://cloud.githubusercontent.com/assets/8047457/9202018/c9ce0a00-401d-11e5-8805-e5ab5684f9a9.png)


![help_helpdesksupport_alt](https://cloud.githubusercontent.com/assets/8047457/9202020/cd245902-401d-11e5-9f55-d6642256a118.png)

@tonyalletag

**Comment by tonyalletag** [comment]
Looks great!

**Comment by mparizernc** [comment]
I have tested this locally in IE9,11, Firefox and Chrome and found no issues. Ready for testing on master.

**Comment by jal-vsi** [comment]
Tested/Passed in Master (IE9/11, FF, CH). The links (help, chirp, pin, chat, blog) go to an undefined web (has to be defined/configured on the high side). The mail links (contact help, give feedback, submit a request) go to Outlook (has to be configured on the high side).

**Comment by mparizernc** [comment]
Tested this in staging against IE10, FF and Chrome. All of the links worked as expected.  There is an issue in IE10 that causes an email to not work as expected on staging.  That is outside of the scope of this ticket.
