### ISSUE TITLE
Personalize/Setting option doesn't work

### ISSUE THREAD

**Issue by jal-vsi** [ozone-development/ozp-center#356]
Select Menu, then 'Settings' under Personalize: the option to "Open in Webtop" doesn't work.  It will save the change correctly but Apps opened afterwards using Quick Launch still "Open in New Tab".  Tested in all 4 browsers.

This 'Setting' option only affects how apps are launched from HUD.

**Comment by tonyalletag** [comment]
@jal-vsi I believe this setting is only to to change the behavior when launching from HUD.  Does the setting change the default behavior when clicking on an app from the HUD?

**Comment by jal-vsi** [comment]
Yes, it changes the default setting in HUD.  Since the capability to change
the way apps are deployed in HUD is already in the HUD page menu, I
recommend deleting that capability in Center (i.e., no need to have that
function in two places so remove it from the Center menu).

On Mon, Oct 12, 2015 at 1:15 PM, tonyalletag <notifications@github.com>
wrote:

> @jal-vsi <https://github.com/jal-vsi> I believe this setting is only to
> to change the behavior when launching from HUD. Does the setting change the
> default behavior when clicking on an app from the HUD?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ozone-development/ozp-center/issues/356#issuecomment-147465968>
> .
>



-- 

Thanks,

Jim Laughter

Systems Test

Ventura Solutions Inc.

131 National Business Parkway

Suite 120

Annapolis Junction, MD 20701

(301) 623-4156

jlaughter@vsi-corp.com

**Comment by tonyalletag** [comment]
This functionality is confusing. Looking for recommendation from @bhalt.

The common tool bar "Settings" does the following:
Center - option to changes default application launch in HUD
HUD - option to changes default application launch in HUD
Webtop - not options

Should the Settings option in Center change the default application launch in HUD? If so we should update the text  
Should the Settings Modal contain all options across Center, HUD, and Webtop?

**Comment by bhalt** [comment]
Ideally, we should have one global Settings modal that contains all settings for HUD, Center, and Webtop. Wherever in the platform you access the Settings modal from, that section's tab would be initially active. This would also provide clarity as to which settings affect which areas of the platform. See screenshot below:

![settings_modal](https://cloud.githubusercontent.com/assets/8047457/10458872/fa1626bc-719a-11e5-94b1-cb69966f6685.PNG)

However, do we have more settings coming soon for HUD, Center and Webtop? If we don't have immediate plans to greatly expand this area, I'm not sure this one current HUD setting deserves an entire Settings modal. Maybe in the meantime we should remove the Settings modal and place this HUD setting inline, inside of HUD. As a general rule, inline settings are much more accessible and intuitive to users, since the user finds the solution at the same place that they had the problem and the same place that they will then access the results.
![hud_defaultlaunchsetting](https://cloud.githubusercontent.com/assets/8047457/10459654/899ffd8c-719e-11e5-829a-08061c44969e.PNG)

At this point, Webtop settings/options are mostly inline as well (grid/desktop view, cascade windows, fullscreen). I think the platform is stronger and more intuitive if we can place as many settings/options inline as possible. Global options that relate directly to the user and can't be inline (such as color themes) should maybe belong in an expanded Profile modal down the road.

Thoughts? @tonyalletag

**Comment by tonyalletag** [comment]
I agree the inline settings/options are more intuitive and we don't have enough settings yet for a global setting modal.

**Comment by bhalt** [comment]
After sprint discussion, alternative HUD location for this feature.

![hud_defaultlaunchsetting3](https://cloud.githubusercontent.com/assets/8047457/10489186/f3b475b0-7269-11e5-91a5-ca29cf6b5251.PNG)

In the future, if we continue with the [custom HUD](https://github.com/ozone-development/ozp-documentation/wiki/Customized-HUD), it may make sense to place this feature in a settings option on My Bookmarks, just like the other HUD widgets would have settings. See below:

![hud_defaultlaunchsetting4](https://cloud.githubusercontent.com/assets/8047457/10489829/86939fda-726c-11e5-8105-fd450e04aace.PNG)

If that isn't in the works for now, we could place this feature inline as shown above. Thoughts @tonyalletag?

**Comment by bhalt** [comment]
Solution discussed and agreed upon -- we are removing the ability to open apps from HUD into Webtop (currently broken), removing the setting to change the default launch (currently in the setting modal), and removing the setting modal on the global menu.

**Comment by tonyalletag** [comment]
Will be completed with:
https://github.com/ozone-development/ozp-center/issues/438
https://github.com/ozone-development/ozp-webtop/issues/648
https://github.com/ozone-development/ozp-hud/issues/143
https://github.com/ozone-development/ozp-hud/issues/142
