### ISSUE TITLE
Responsiveness - App Listings do not fill all columns of Center Discovery

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#366]
Depending on the number of columns shown the Most Popular list can have empty slots listed before the Load More button is shown:

![image](https://cloud.githubusercontent.com/assets/7015118/9411599/ebd5eb3e-47f4-11e5-992f-e2a7f6b37367.png)

Can/should our request for icons be a multiple of the number of columns shown?

Should we move the Load More button so that we have less blank space on the page?

**Comment by bhalt** [comment]
Ideally, our request for icons should be a multiple of the number of columns shown. Is this possible / time-intensive to do?

**Comment by tonyalletag** [comment]
Can we remove the load more button and auto fill and load more apps when a user scrolls down?

**Comment by wski** [comment]
My concerns with this is that I'd like to avoid guessing how many tiles can fit on a row given the browser window size. Will investigate a clean way to calculate and report back.

**Comment by wski** [comment]
So because we just use class `.row` it will pipe as many listing tiles that will fit before wrapping and pushing the rest to the next row. (this is not limited to two rows)

After looking over a few things the listing tile is `220px by 192px` a solution would be to find how much space is available in `.listings-search-results`, divide that by `220px` and find out how many listing tiles can fit in that space. 

Next we need to decide how many rows should be filled before we make our request to the backend. This is where it becomes a bit more complex. If we decide on two rows, and the users browser is really small, we might only get 2-3 listing tiles per row for a total of 4-6 tiles shown. 

Assuming this is okay we have something else to think about, If the user rescales their browser do we want to make another request to the backend to fill the newly expanded `.listings-search-results` which could now fit twice as many listing tiles (or more). If not we will still get the result shown above if they increase the browser window size. I think this is something that needs to be discussed and address possible overheads of each solution.

**Comment by wski** [comment]
Regardless of the above the space should fill in during infinite so if we are not as concerned about filling out the screen evenly it is a much simpler task.

**Comment by wski** [comment]
@tonyalletag when we talked we discussed the infinite scroll functionality, however it doesn't seem like this ticket is talking about that. As mentioned above I think that the technical challenge of filling the columns could be a guessing game mixed with assigned amount of rows. Should I be looking elsewhere for the issue on infinite scroll load more?

**Comment by tonyalletag** [comment]
OBE
