### ISSUE TITLE
Implement Private Listings

### ISSUE THREAD

**Issue by blaino** [ozone-development/ozp-center#447]
The new backend will deploy with a preliminary version of tailored access. One aspect of tailored access is the ability to make Apps Mall listings private. In particular, we need the following:

1. Org and Apps Mall stewards shall have the ability toggle whether or not the app is private in the Quickview Administration tab. 
2. Those submitting or editing listings shall have the ability to toggle whether or not the app is private in the create/edit page. 
3. The create/edit page shall note that apps set to private should include a justification in the Usage Requirements field. 
4. The table view in Listing Management shall have a column indicating whether or not the listing is private.
5. Private listings in the tile view in Listing Management shall have a lock icon in their footers.

**Comment by blaino** [comment]
@tonyalletag, @bhalt, and @arw180, please take a quick look to ensure I captured our discussion.

**Comment by bhalt** [comment]
:+1:

**Comment by tonyalletag** [comment]
:+1:

**Comment by bhalt** [comment]
After looking at this further, I think we should only show the Private toggle inside the Create/Edit form. The two toggles currently inside the Quickview Administration tab are post-publish settings (not done through the Create/Edit form), whereas the Private feature is a pre-publish setting. The two post-publish toggles (Enable/Disable and Feature on Homepage) make sense to do after a listing is published, but the Private setting is something that most orgs will likely want to ensure upon creation. Keeping this in the Create/Edit form (rather than the Quickview Admin tab) would also keep this feature from becoming trivial. We want users to think of this as a setting baked into the app on creation, with appropriate Center Steward oversight. Always editable; but impactful with potentially far-reaching consequences.

With those adjustments, below is the implementation I would propose:

-----
**1)** Org stewards, Center stewards, and those submitting or editing listings should have the ability to toggle whether or not the app is private in the Create/Edit page. This field should include a note that apps set to private must include a justification in the Usage Requirements field.

![center_privatelisting_edit](https://cloud.githubusercontent.com/assets/8047457/11566104/f9e310ce-99ae-11e5-8de6-e6e91aa73c2e.png)
![center_privatelisting_edit_selected](https://cloud.githubusercontent.com/assets/8047457/11566108/ff5cfd76-99ae-11e5-8769-96711795a9ee.png)

-----
**2)** Private listings in the Center should have a lock icon wherever the Org badge is shown (See example for Announcing Clock app below - both tile view and quickview). [**Implementation:** Icon is already in project. Insert icon into *span.company*: `<span class="company"><i class="icon-lock-blue"></i> ORG</span>`]

![center_privatelisting_tile](https://cloud.githubusercontent.com/assets/8047457/11566120/0c91475e-99af-11e5-9c7e-e7f763e1c89c.png)
![center_privatelisting_quickview](https://cloud.githubusercontent.com/assets/8047457/11566122/0ee35768-99af-11e5-9190-0edab6fba31e.png)

-----
**3)** The table view in Listing Management should have a column indicating whether or not the listing is private.

![center_privatelisting_management](https://cloud.githubusercontent.com/assets/8047457/11566135/20675bd8-99af-11e5-882b-482e5f70af85.png)

-----
**4)** The tile view in Listing Management should have an icon indicating if the listing is private. Duplicate to every tab (My Listings, each Org Listings tab, All Center Listings).

![center_privatelisting_management_tile](https://cloud.githubusercontent.com/assets/8047457/11566465/91513214-99b0-11e5-8b34-0fea71515bce.png)

-----
**5)** Any change of Public/Private status should show as a notification in the Recent Activity feed in order to make any change very visible to Admin.

![center_privatelisting_management_activity](https://cloud.githubusercontent.com/assets/8047457/11566696/8a1a0bbe-99b1-11e5-8ec7-50e5ed5a85f3.png)

**Comment by tonyalletag** [comment]
Good to go with this implementation

**Comment by blaino** [comment]
In regards to #5, handling the Recent Activity, we get a basic capability for free (no code change): 

![screen shot 2015-12-11 at 10 57 15 am](https://cloud.githubusercontent.com/assets/1998900/11748377/fa6933be-9ff5-11e5-9a4d-dcd5eeed7e60.png)

The page is written to generically provide these sorts of updates. It does not call it out as special but the information is there. I'm leaving things alone for this ticket, but on Tuesday let us revisit and if we want a special case, let's write a separate ticket.

**Comment by bhalt** [comment]
@blaino No need - that's good for now! Wasn't sure what the existing functionality was.

**Comment by tdressel** [comment]
Not yet implemented on center and waiting for Alan.

**Comment by tdressel** [comment]
Everything passed except org stewards are not able to see listing when it is set to private therefore they cannot approve it. Create bug #509

**Comment by tdressel** [comment]
Private Listings are suspended until further notice.  Button has been removed from UI but backend is still in place for future.
