### ISSUE TITLE
Add security marking to listings and associated image files

### ISSUE THREAD

**Issue by blaino** [ozone-development/ozp-center#448]
Every listing and every associated image file will need a valid CAPCO marking. We will eventually integrate with the Boostrap Classify library for handling the myriad possible classifications. This ticket is to pave the way for this eventual integration. In particular we need the following:

1. The create/edit page shall include as its first item a field for the security marking. 
2. Each image field (icons, banners and screenshots) shall include an additional field for its security marking. 
3. A modal, activated by a button, shall stand in for the Boostrap Classify modal, allowing the user to select a test classification level. 
4. The Quickview Details tab shall include the security marking. 
5. Listing Management's table view shall include a column with the security marking.

**Comment by blaino** [comment]
@tonyalletag, @clarkjefcoat, @arw180, and @bhalt, please take a quick look to ensure I captured our discussion.

**Comment by bhalt** [comment]
:+1:

**Comment by tdressel** [comment]
Alan is still working on getting the CI box up and running.

**Comment by tdressel** [comment]
1. - The create/edit page shall include as its first item a field for the security marking.  - PASSED.  Tested the security marking was there and working according to user's privs. Gave user friendly error upon save when high portion marking than what user was allowed.
2. - Each image field (icons, banners and screenshots) shall include an additional field for its security marking. PASSED- Jpg, Png and gifs using valid and invalid marking for each.
3. - A modal, activated by a button, shall stand in for the Boostrap Classify modal, allowing the user to select a test classification level. PASSED- Jpg, Png and gifs using valid and invalid marking for each.
4. - The Quickview Details tab shall include the security marking. PASSED shows accurate marking.
5. - Listing Management's table view shall include a column with the security marking.  - NOT TESTED - need a new cert in order to publish listing and see in table view.

**Comment by tdressel** [comment]
Passed on Latest

**Comment by tdressel** [comment]
These have been added.

**Comment by tdressel** [comment]
Passed on staging.
