### ISSUE TITLE
Can't upload a jpg format to listing

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-center#487]
STR-
Go to Submit a Listing
Upload a JPG image
Save
RESULTS - 500 Internal Error in dev console.  App just spins as if it is saving forever.
EXPECTED RESULTS - Should Save Listing.

**Comment by blaino** [comment]
From @arw180:

It looks like the problem was with nginx - the request was never reaching the backend. For larger files, nginx writes them to disk before sending them on their way to the backend. For some reason, the temporary directory inside of /usr/local/nginx where these larger files get written was owned by root (as opposed to the nginx user), and so I was seeing permission denied errors in the nginx log (/usr/local/nginx/logs/error.log) very similar to the report here: https://blog.lysender.com/2015/05/nginx-cannot-upload-regular-sized-files-permission-denied/

After a manual sudo chown -R nginx /usr/local/nginx, everything seems to work fine. 

I modified our Ansible scripts that deploy nginx to make sure the permissions are set correctly, so hopefully this won't be an issue in the future.
