### ISSUE TITLE
Quickview Modal - Admin tab record for approval is truncated

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#567]
In the Quickview Modal in the Admin tab under "Listing Changes" after a listing a approved by an Org Steward there is a message that says "<Org Steward> approved the listing for".  But nothing is shown after the word "for".

The name of the Org that approved this listing should be shown after "for".

![approvedfor](https://cloud.githubusercontent.com/assets/7015118/14045623/03ad0f1c-f272-11e5-82d6-5e82bc094ce2.png)

**Comment by rkenyon1969** [comment]
Is the approving org the org of the person approving or can the person approving choose an org to approve for?

**Comment by clarkjefcoat** [comment]
The approving org must be the same as the Associated Org from the listing.

**Comment by rkenyon1969** [comment]
Second thought. I don't think "approved the listing for" is talking about the agency, but instead the user. I assumed agency because the code read "change.listing.agency". However, I've changed it to "change.author.user.username" to show the author whom it has been approved for. Your thoughts?

![screenshot from 2016-04-11 13 59 33](https://cloud.githubusercontent.com/assets/18191566/14437099/b41e9c3e-ffed-11e5-8ab0-2270b95b2560.png)

**Comment by rkenyon1969** [comment]
Ok - not looking for user, but agency listing was created for.

**Comment by rkenyon1969** [comment]
Please review:

@clarkjefcoat 
@wski

**Comment by rkenyon1969** [comment]
This is a duplicate of #580 which has been approved, merged and branch deleted.

**Comment by clarkjefcoat** [comment]
Developers should not close issues.  Please leave open and let testers handle it.

**Comment by tdressel** [comment]
Passed on Staging.
