### ISSUE TITLE
Listing Management - Recent Activity should show submitted listings

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#577]

**Comment by mannyrivera2010** [comment]
![image](https://cloud.githubusercontent.com/assets/1072762/14364014/e8df3b5c-fcd4-11e5-8637-0c977a2e1c5b.png)

It seems to be working

**Comment by clarkjefcoat** [comment]
Try this as a normal user and not as an Admin.

**Comment by akonsowski** [comment]
Issue moved to [ozone-development/ozp-backend #167](https://github.com/ozone-development/ozp-backend/issues/167) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by akonsowski** [comment]
after making changes to the front end i am not getting expected results form the backend.
 received 
![image](https://cloud.githubusercontent.com/assets/18122042/15334224/4654f1f2-1c3b-11e6-8d58-bbd797074bb7.png) instead of 
![image](https://cloud.githubusercontent.com/assets/18122042/15334246/600e787a-1c3b-11e6-9d8d-8e8b77136594.png) 
@mannyrivera2010

**Comment by tdressel** [comment]
Passed on latest.

**Comment by tdressel** [comment]
Passed on staging
